version: '2'

env:
  TERM: screen-256color
  GO111MODULE: on
  AWS_DEFAULT_REGION: eu-west-1

tasks:
  default:
    cmds:
    - task: test

  test:
    desc: Run tests.
    cmds:
    - task: test-go
    - task: test-terraform

  test-go:
    desc: Run tests for all Go code.
    silent: true
    cmds:
    - gofmt -s -l -w .
    - go vet -v ./...

  test-terraform:
    desc: Run tests for all terraform directories.
    silent: true
    env:
      DIRECTORIES:
        sh: find . -type f -name '*.tf' -not -path "**/.terraform/*" -print0 | xargs -0I {} dirname {} | sort -u
    cmds:
    - |
      BOLD=$(tput bold)
      NORM=$(tput sgr0)

      CWD=$PWD

      for d in $DIRECTORIES; do 
        cd $d
        echo "${BOLD}$PWD:${NORM}"

        if ! terraform fmt -check=true -list=false -recursive=false; then
          echo "  ✗ terraform fmt" && exit $?
        else
          echo "  √ terraform fmt"
        fi

        if ! terraform init -backend=false -input=false -get=true -get-plugins=true -no-color > /dev/null; then
          echo "  ✗ terraform init" && exit $?
        else
          echo "  √ terraform init"
        fi

        if ! terraform validate > /dev/null; then
          echo "  ✗ terraform validate" && exit $?
        else
          echo "  √ terraform validate"
        fi

        cd $CWD
      done

  e2e:
    desc: Run the end 2 end test suite.
    silent: true
    cmds:
    - go test -v ./... -timeout=1h
    